### ISSUE TITLE
A question about initializing model

### ISSUE THREAD

**Issue by HJJ124** [jleinonen/cloudsat-gan#1]
File "/root/tf/cloudsat-gan/csmodiscgan/src/train.py", line 38, in load_model_state
    gan._make_train_function()
AttributeError: 'Functional' object has no attribute '_make_train_function'

After git it and run
 ‘ python main.py train --scenes_file=../../../cs_modis_scenes.nc’
Model will be trained successfully but after loading weights, Error will be shown as above
If plot directly with
 ‘ python main.py plot --scenes_file=../../../cs_modis_scenes.nc
This problem will be shown directly.

**Comment by jleinonen** [comment]
Hi, this code is fairly old and was designed to be run with TensorFlow 1.X. I think somebody else also noted the same issue while using TF 2. Would it be possible for you to try it in a TF1.X environment?
